apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 71e4cc9606f4a1f572084e34a1cbb08ac28609e7
resources:
- ../base
