apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 10.101.209.206:8761/dockertest
  newTag: eb745f72058fa77e4a14fc552341c3e405f2dd2e
resources:
- ../base
