apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 10.101.209.206:8761/dockertest
  newTag: deab36370eebeef4ae6c27ed4e4eb205705a98b1
resources:
- ../base
