apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 10.101.209.206:8761/dockertest:e0b0d1d992c9dbf6843a3da0903f759e097c0b8e
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: mydockercredentials
